### ISSUE TITLE
Incorrect ADC code to voltage conversion formula

### ISSUE THREAD

**Issue by sjpark608** [EdgePi-Cloud/edgepi-python-sdk#262]
https://github.com/EdgePi-Cloud/edgepi-python-sdk/blob/f17baf792a7b2eedea04f8b10bef98e5a81b6514/src/edgepi/adc/adc_voltage.py#L55-L80

Line 73 and 74 forces the sign bit to zero. This isn't the correct way to perform the negative number conversion.

**Comment by farzadpanahi** [comment]
is this a bug? can you provide more details?

**Comment by sjpark608** [comment]
> is this a bug? can you provide more details?

Yes this is a bug, I'm Opening a PR soon
