### ISSUE TITLE
EdgePi Thermocouple Module User Guide has a code error

### ISSUE THREAD

**Issue by ikohOsensa** [EdgePi-Cloud/edgepi-python-sdk#276]
in the "Automatic Measurements" block of code

line 2 from edgepi.edgepi_tc import EdgePiTC

should be 

from edgepi.tc.edgepi_tc import EdgePiTC

missing the tc

**Comment by sjpark608** [comment]
![image](https://user-images.githubusercontent.com/78987042/222244127-e8d6fac3-a0c0-436c-8350-cc214e0176bd.png)

if you go into the file and highlight the lines with the issue and click on the reference in th new issue, this way you don't have to describe where the issue is :) @ikohOsensa

**Comment by ikohOsensa** [comment]
Nice nice
