### ISSUE TITLE
Make channel numbering consistent

### ISSUE THREAD

**Issue by farzadpanahi** [EdgePi-Cloud/edgepi-python-sdk#289]
Channel numbers should be consistent across all EdgePi systems. On the label channels start from `1`. In the UI is the same. We should make it consistent across all of our systems. Otherwise there will always be confusion. So for ADC, DAC, DIN, DOUT and LED numbering should start from 1.

We just need to make sure that the public interface of the SDK works with 1..8 channels. This shouldn't affect anything underneath.

**Comment by farzadpanahi** [comment]
@jarell-santella keep an eye on this issue to update your daemons.

**Comment by sjpark608** [comment]
Public interface of modules use indexing 1~8
