### ISSUE TITLE
DAC gain should change the range, and not just the voltages being read

### ISSUE THREAD

**Issue by jarell-santella** [EdgePi-Cloud/edgepi-python-sdk#290]
Gain setting should not affect the voltages being read back. When writing voltages to DAC with gain disabled, the voltage will be read back as half (i.e. write 4 volts to DAC, this will be read back as ~2). However, when the gain is enabled, the voltage will be read back correctly (i.e. write 4 volts to DAC, this will be read back as ~4). Gain should only change the range that voltages can be inputted, rather than how they are read when they are inputted.

**Comment by sjpark608** [comment]
There are few hardware related issue cause this DAC voltage issue.
1. The Power-on-reset setting of DAC_GAIN GPIO pin
2. The internal DAC_GAIN amplifier

```
>>> from edgepi.dac.dac_constants import DACChannel as Ch
>>> from edgepi.dac.edgepi_dac import EdgePiDAC
>>>
>>> edge_dac = EdgePiDAC()
>>> edge_dac.get_state(Ch.AOUT1, True,True,True)
(0, -0.01619785465300083, True)
>>> edge_dac.write_voltage(Ch.AOUT1, 1.000)
6619 # P-1
>>> edge_dac.get_state(Ch.AOUT1, True,True,True)
(6619, 1.0162652694642433, True)
>>> edge_dac.enable_dac_gain(False)
False
>>> edge_dac.get_state(Ch.AOUT1, True,True,True)
(6619, 0.5000337074056213, False)
>>> edge_dac.write_voltage(Ch.AOUT1, 1.000)
13029 # P-2
>>> edge_dac.get_state(Ch.AOUT1, True,True,True)
(13029, 0.9999648620809147, False)
>>> edge_dac.enable_dac_gain(True)
True
>>> edge_dac.get_state(Ch.AOUT1, True,True,True)
(13029, 2.0161275788148303, True)
>>>
```
On power-on-reset, DAC_GAIN GPIO pin is configured with input direction and state high. get_state() method only checks the state of the pin. As a result, it thinks the DAC_GAIN is enabled when it is not. Therefore the writing 1.000V at P-1 above result in the code value equivalent to 1.000V when DAC_GAIN is enabled. The actual measured voltage is 0.5V. When enable_dac_gain(False) is called, the DAC_GAIN pin is configured to output a low state that actually enforces the state. As a result, the dac_get_state() call returns the correct voltage.
At P-2 when 1.000V is written to the channel, the measured voltage matches the written voltage.

When enable_dac_gain(True) is called, the internal gain is enabled. This internal gain affects the voltage directly without changing the code value in the memory. 

A suggested fix for this issue would be determining the range of voltage before writing voltage to any channel after instantiating the DAC module. Or when the range of voltage changes, it also calls write voltage to modify the code values of each active channel to accommodate the change in gain.

**Comment by sjpark608** [comment]
@farzadpanahi @jarell-santella 

There's an edge case for enable_dac_gain()

the current implementation of enable_dac_gain() has a flag to re-write channel code values when the dac_gain is enabled or disabled.
ex)
enable_dac_gain(True, True)
this reads the code value of each channel and divides the value by 2 then writes it back to the channel. This way, the output voltage stays the same.
enable_dac_gain(False, True)
this does the opposite of the above example. Instead of dividing the code value by 2, it multiplies. However, it only works when the code value is less than half of the maximum range.

To avoid writing the value greater than the maximum code value, it has a condition to check whether the current code value is less than Max_code/2. If it is greater, the code will stay the same.

**Comment by farzadpanahi** [comment]
@sjpark608 I am not sure what is the best solution for this edge case.  the other option is to set it to max in this edge case. because I think the behaviour you mentioned is what will happen in (False, False) scenario.

**Comment by sjpark608** [comment]
> @sjpark608 I am not sure what is the best solution for this edge case. the other option is to set it to max in this edge case. because I think the behaviour you mentioned is what will happen in (False, False) scenario.

This edge case is for (False, True) where we want to match the output voltage to what it shows on the dashboard after disabling the DAC_GAIN.

ex) 
1. Initially the DAC is set to range 0~10 and 7V. 
2. The user wants to change the DAC range back to 0~5.
3. If the backend call (False, False), the DAC will just output 3.5V. If (False True) is called, it'd try multiplying the current code value with 2 to keep the current output voltage in the dashboard. However, the value would be over the maximum allowable code value.

**Comment by farzadpanahi** [comment]
as discussed let's throw exception in edge case
