### ISSUE TITLE
DAC write voltage

### ISSUE THREAD

**Issue by iaj2** [EdgePi-Cloud/edgepi-python-sdk#305]
```
from edgepi.dac.edgepi_dac import EdgePiDAC

# Init DAC
edgepi_dac = EdgePiDAC()

edgepi_dac.set_dac_gain(True)

# Write 2 volts to ouput 1
edgepi_dac.write_voltage(1,2)

# Read voltage from output 1
edgepi_dac.read_voltage(1)
```

Gets Traceback:

Traceback (most recent call last):
  File "/home/tf1/venv/projects/AutoFanProject/test_dac_fan.py", line 9, in <module>
    edgepi_dac.write_voltage(1,2)
  File "/home/tf1/venv/lib/python3.9/site-packages/edgepi/dac/edgepi_dac.py", line 120, in write_voltage
    self.dac_ops.check_range(analog_out.value, 0, NUM_PINS-1)
AttributeError: 'int' object has no attribute 'value'

**Comment by sjpark608** [comment]
https://github.com/EdgePi-Cloud/edgepi-python-sdk/tree/dev/src/edgepi/dac

README on the main branch is not up to date. Please use the README in dev branch
