### ISSUE TITLE
re-investigate the file system behaviour of PWM character device

### ISSUE THREAD

**Issue by sjpark608** [EdgePi-Cloud/edgepi-python-sdk#316]
PWM signal stops working when the character device is not closed correctly.

```python
(venv_test) integtest@integTest:~/projects/edgepi-python-sdk/src $ python
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from edgepi.pwm.pwm_constants import Polarity, PWMPins
>>> from edgepi.pwm.edgepi_pwm import EdgePiPWM
>>> edge_pwm = EdgePiPWM(PWMPins.PWM1)
>>> edge_pwm.set_frequency(1000)
>>> edge_pwm.set_duty_cycle(50)
>>> edge_pwm.get_enabled()
False
>>> edge_pwm.enable()
>>> quit()
```
quit without closing the device

```python
(venv_test) integtest@integTest:~/projects/edgepi-python-sdk/src $ python
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from edgepi.pwm.pwm_constants import Polarity, PWMPins
>>> from edgepi.pwm.edgepi_pwm import EdgePiPWM
>>> edge_pwm = EdgePiPWM(PWMPins.PWM1)
>>> edge_pwm.get_enabled()
True
>>> edge_pwm.enable()
# signal not generated
>>> edge_pwm.disable()
>>> edge_pwm.enable()
# signal starts to show
```

**Comment by sjpark608** [comment]
There's no need to call close().
- in above scenario, it only requires calling disable() then enable() again to get the PWM working again

**Comment by sjpark608** [comment]
To avoid avoid the above edge case, I propose the following solution
1. set_config method (pwm_num, frequency, duty_cycle, polarity)
   - only called for the first time it is being initiated
   - handles configuring specified pwm
   - checks whether the PWM is already enabled, if it is, disable it.

**Comment by farzadpanahi** [comment]
> To avoid avoid the above edge case, I propose the following solution
> 
> 1. set_config method (pwm_num, frequency, duty_cycle, polarity)
>    
>    * only called for the first time it is being initiated
>    * handles configuring specified pwm
>    * checks whether the PWM is already enabled, if it is, disable it.

@sjpark608 I think this is a good idea. user needs to call enable after set_config, right?
also I think you need a check in enable function to see if it is already enabled do not enable it. is that right?

**Comment by sjpark608** [comment]
@farzadpanahi  @jarell-santella 

Re-tested opening the same PWM device in separate processes.
1. As long as it is not accessing the file at the same time, a separate process can access the same device
2. if one process closes the device, the device is also closed on the other process

**Comment by farzadpanahi** [comment]
@sjpark608 what happens if they try to access the file at the same time?

**Comment by sjpark608** [comment]
I guess this issue is resolved with what we found during device manager and collector troubleshooting
