### ISSUE TITLE
error in Thermocouple Module ReadMe

### ISSUE THREAD

**Issue by iaj2** [EdgePi-Cloud/edgepi-python-sdk#335]
In methods guide table under set_config inputs, I believe it should be TCHighMask and not TCLHighMask

<li>
                    <p><code>tc_high_mask</code> (<code>TCLHighMask</code>): choose whether to mask TCHIGH fault from asserting through the FAULT pin</p>
                </li>

**Comment by farzadpanahi** [comment]
@iaj2 please send a PR to fix this issue.
