### ISSUE TITLE
EEPROM Refactor

### ISSUE THREAD

**Issue by sjpark608** [EdgePi-Cloud/edgepi-python-sdk#350]
- [x] Set_edgepi_reserved_data
   - [x] one method passes parameters 
   - [x] another method passes dataclass
   - [x] delete messageField enum
- [x] read/write bin file to reset
   - [x] requires matching md5sum to perform
- [x] move eeprom out of calibration folder

**Comment by farzadpanahi** [comment]
please add the following as well:
1. rename `eeprom_reset` -> `reset_user_space`
2. rename `write_memory` -> `write_user_space`
3. rename `read_memory` -> `read_user_space`
4. class `EdgePiEEPROMData` should be in its own file
5. what is the use of `init_memory` func? I cannot find the reference calls. not even sure what the purpose is. it is returning is_full, is_empty !
6. rename `set_edgepi_reserved_data` -> `set_edgepi_data`
7. rename `get_edgepi_reserved_data` -> `get_edgepi_data`
8. add new method: `set_edgepi_data_class`
9. (optional) I would try to simplify  `EdgePiEEPROMData` and get rid of pack/unpack stuff as much as possible.
